# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [1]:
from numpy import *

In [4]:
a=array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [5]:
zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [6]:
linspace(0, 5, 10)


array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [11]:
eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [62]:
random.rand(4,4)

array([[0.6069516 , 0.12829785, 0.46235467, 0.8322923 ],
       [0.01979868, 0.63459511, 0.82081466, 0.38816322],
       [0.16493764, 0.42244219, 0.48490056, 0.35031172],
       [0.95447964, 0.5362816 , 0.18116502, 0.20549931]])

---

### Exercise 6:
Find the shape of a NumPy array.

In [25]:
a=array([1, 2, 3,4,5])
a.shape



(5,)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [41]:
arange(1, 17).reshape((4, 4))



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [122]:
random.randint(1,16,(4,4))

array([[ 9,  9, 10, 13],
       [ 6,  4,  1, 11],
       [13,  4,  9, 13],
       [ 6,  4,  6,  4]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [48]:
a=array(16)
print(a.dtype)


int64


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [55]:
a=arange(1,101)
a[(a%2==0)]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [60]:
random.randint(10,50,size=(6,6))

array([[19, 26, 18, 30, 25, 24],
       [45, 42, 15, 24, 28, 18],
       [45, 25, 17, 27, 42, 46],
       [42, 17, 29, 26, 48, 21],
       [22, 34, 14, 40, 13, 27],
       [18, 47, 26, 20, 24, 44]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [64]:
a=array([[1,2,3],[4,5,6]])
b=a[0,]
b

array([1, 2, 3])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [68]:
a=array([1,2,3,4,5,6,7,8,9,0])
sum(a)


45

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [77]:
a=array([1,2,3,4,5,6])
mean(a),median(a),std(a)



(3.5, 3.5, 1.707825127659933)

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [81]:
max(a),min(a)

(6, 1)

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [94]:
a=random.randint(0,20,20)
print(a)

[12  6  6  9 15  9 14  4  9  9 19  9  4  1 14 13  1 15 10 15]


In [95]:
a.argmax()

10

---

### Exercise 16:
Create a NumPy array and reverse its elements.

In [125]:
a=arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [126]:
flip(a)#reverse functions

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [136]:
#help(random.rand)
random.random((10, 7))

array([[0.93598175, 0.76473399, 0.28122322, 0.73729041, 0.16032503,
        0.68734243, 0.78678847],
       [0.04897752, 0.94050859, 0.55082056, 0.73739633, 0.54595648,
        0.96405086, 0.30784512],
       [0.61123894, 0.920043  , 0.37884544, 0.15888158, 0.49872508,
        0.73493424, 0.58490512],
       [0.83959877, 0.64385312, 0.69277612, 0.84744268, 0.18493815,
        0.24676202, 0.49740215],
       [0.74022249, 0.64635671, 0.69175552, 0.06073312, 0.29761615,
        0.04204213, 0.18589261],
       [0.3521034 , 0.2792237 , 0.48460307, 0.85170558, 0.98083652,
        0.40613886, 0.19004627],
       [0.76573962, 0.67628484, 0.6666988 , 0.76816575, 0.60267456,
        0.26296271, 0.12932136],
       [0.63937811, 0.12696264, 0.13723344, 0.70856476, 0.04197341,
        0.03593501, 0.58643879],
       [0.1304916 , 0.45926029, 0.63385628, 0.28761794, 0.03695451,
        0.33497956, 0.61470547],
       [0.43675781, 0.15603293, 0.39119642, 0.98893364, 0.58982108,
        0.84269701, 0.1

In [134]:
help(random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [140]:
a=random.randint(1,9,(3,3))
print(a)
print('\n')
b=random.randint(9,18,(3,3))
print(b)
print('\n')
c=a*b
print(c)

[[4 2 8]
 [4 6 5]
 [5 6 4]]


[[12 10 15]
 [14 15 17]
 [12 16 11]]


[[ 48  20 120]
 [ 56  90  85]
 [ 60  96  44]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [153]:
a=arange(1,9)
diag(a)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [165]:
a=random.randint(1,9,(2,5))
print(a)
print('\n')
b=random.randint(9,18,(2,5))
print(b)
print('\n')
c=b*a
print(c)

[[7 2 5 1 6]
 [3 1 5 7 3]]


[[10 12 11 16 16]
 [15 16 13 11 17]]


[[70 24 55 16 96]
 [45 16 65 77 51]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [163]:
a=random.randint(1,9,(2,5))
a

array([[1, 5, 1, 6, 8],
       [7, 7, 4, 3, 2]])

In [164]:
a.flatten()

array([1, 5, 1, 6, 8, 7, 7, 4, 3, 2])

---

### Exercise 21:
Stack two NumPy arrays vertically.

In [173]:
a=random.randint(1,5,(1,5))
print(a)
print('\n')
b=random.randint(6,11,(1,5))
print(b)
print('\n')
vstack((a,b))

[[3 4 1 2 2]]


[[8 8 7 9 9]]




array([[3, 4, 1, 2, 2],
       [8, 8, 7, 9, 9]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

In [174]:
a=random.randint(1,5,(1,5))
print(a)
print('\n')
b=random.randint(6,11,(1,5))
print(b)
print('\n')
hstack((a,b))

[[1 2 1 4 2]]


[[7 8 7 9 9]]




array([[1, 2, 1, 4, 2, 7, 8, 7, 9, 9]])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [183]:
a=random.randint(1,10,(8,8))
split(a,2)

[array([[4, 4, 7, 3, 9, 4, 8, 3],
        [4, 1, 9, 7, 7, 7, 4, 4],
        [5, 3, 3, 1, 5, 5, 9, 9],
        [2, 7, 8, 2, 7, 2, 9, 9]]),
 array([[4, 2, 8, 3, 4, 4, 4, 5],
        [2, 6, 1, 5, 6, 8, 5, 2],
        [3, 8, 2, 5, 1, 3, 7, 5],
        [6, 2, 3, 8, 2, 5, 6, 9]])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [201]:
import numpy as np
a=random.random((1,5))
a
np.round(a,2)


array([[0.38, 0.52, 0.52, 0.1 , 0.27]])

---

### Exercise 25:
Find the unique elements of a NumPy array.

In [203]:
a=random.randint(1,10,(8,8))
print(a)
print('\n')
unique(a)

[[1 8 5 5 5 8 9 2]
 [7 9 9 4 5 7 1 3]
 [3 8 7 3 4 6 3 7]
 [6 6 6 9 3 7 8 6]
 [8 9 3 8 5 4 5 6]
 [4 8 3 7 2 7 7 2]
 [5 8 2 3 3 3 6 3]
 [5 9 6 3 5 6 3 6]]




array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [204]:
a=random.randint(1,10,(8,8))
print(a)
print('\n')

a[a<=8]=8
b=a
print(b)

[[3 3 8 8 9 3 3 6]
 [1 5 6 3 9 9 1 9]
 [5 6 3 1 6 7 2 7]
 [3 3 5 6 4 6 4 7]
 [5 7 2 2 7 6 1 3]
 [6 3 5 1 9 4 3 5]
 [4 5 1 4 8 9 2 5]
 [3 7 6 6 5 7 7 3]]


[[8 8 8 8 9 8 8 8]
 [8 8 8 8 9 9 8 9]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 9 8 8 8]
 [8 8 8 8 8 9 8 8]
 [8 8 8 8 8 8 8 8]]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [205]:
a=random.randint(1,10,(8,8))
print(a)
print('\n')
cumsum(a)

[[3 2 7 7 1 4 8 7]
 [1 1 1 3 3 7 2 6]
 [3 8 2 7 7 7 1 9]
 [3 2 7 3 2 3 4 6]
 [6 8 8 3 8 5 6 5]
 [4 2 9 6 5 5 6 8]
 [7 5 6 1 1 9 4 8]
 [8 7 3 3 3 7 8 2]]




array([  3,   5,  12,  19,  20,  24,  32,  39,  40,  41,  42,  45,  48,
        55,  57,  63,  66,  74,  76,  83,  90,  97,  98, 107, 110, 112,
       119, 122, 124, 127, 131, 137, 143, 151, 159, 162, 170, 175, 181,
       186, 190, 192, 201, 207, 212, 217, 223, 231, 238, 243, 249, 250,
       251, 260, 264, 272, 280, 287, 290, 293, 296, 303, 311, 313])

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [215]:
a=array([[[1,2,3,4],[1,0,2,3,],[4,5,6,7]]])
print(a)
print('\n')
count_nonzero(a)

[[[1 2 3 4]
  [1 0 2 3]
  [4 5 6 7]]]




11

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [217]:
a=random.randint(1,17,(4,4))
print(a)
print('/n')
sort(a)


[[ 6  7  5  5]
 [11  8 10  8]
 [ 1  4  2 14]
 [ 2  2 11  9]]
/n


array([[ 5,  5,  6,  7],
       [ 8,  8, 10, 11],
       [ 1,  2,  4, 14],
       [ 2,  2,  9, 11]])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [219]:
a=random.randint(1,16,(3,3))
print(a)
print('\n')
#column wise
b=sum(a, axis=0)
print(b)
print('\n')
#row wise
c=sum(a, axis=1)
print(c)


[[ 7 14  4]
 [15  2  7]
 [ 6 11  6]]


[28 27 17]


[25 24 23]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [229]:
import numpy as np
a=np.random.randint(1,9,(2,2))
print(a)
print('\n')

b=np.min(a)
print(b)
print('\n')

c=np.max(a)
print(c)
print('\n')


d=(a-b)/(c-b)
print(d)



[[4 5]
 [2 8]]


2


8


[[0.33333333 0.5       ]
 [0.         1.        ]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

In [235]:
a=array([2,2,4])
print(a)
print('\n')
         
b=array([4,4,8])
print(b)
print('\n')

dot(a,b)


[2 2 4]


[4 4 8]




48

---

### Exercise 33:
Find the trace of a square NumPy matrix.

In [244]:
a=random.randint(1,9,(2,2))
print(a)
print('\n')
trace(a)

[[6 4]
 [4 4]]




10

---

### Exercise 34:
Create a 2D array and swap two rows.

In [248]:
a=random.randint(1,10,(3,3))
print(a)
print('\n')
a[[2,0]]=a[[0,2]]
print(a)



[[4 5 4]
 [7 1 6]
 [7 5 2]]


[[7 5 2]
 [7 1 6]
 [4 5 4]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [254]:
a=random.randint(1,10,8)
print(a)
print('\n')
a.reshape(-1,1)

[6 9 7 3 3 3 1 9]




array([[6],
       [9],
       [7],
       [3],
       [3],
       [3],
       [1],
       [9]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

In [256]:
a=random.randint(1,16,(3,3))
print(a)
print('\n')
linalg.det(a)


[[13 13 13]
 [ 2  3 13]
 [ 5 10  1]]




-766.9999999999999

--

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [261]:
a=random.randint(1,17,(2,2))
print(a)
print('\n')

e=linalg.eig(a)# prints first the eigenvalues and then eigenvectors
print(e)






[[16  7]
 [ 7  7]]


(array([19.82165849,  3.17834151]), array([[ 0.87771225, -0.47918807],
       [ 0.47918807,  0.87771225]]))


---

### Exercise 38:
Solve a system of linear equations using NumPy.

In [267]:
a=array([[1,6],[2,3]])
b=array([6,8])
linalg.solve(a,b)

array([3.33333333, 0.44444444])

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

In [270]:
a=random.randint(1,9,9)
print(a)
print('\n')

b=mean(a)
print(b)
print('\n')

c=std(a)
print(c)
print('\n')

d=random.normal(b, c, a.shape)
print(d)
print('\n')

e=a+d
print(e)

[1 7 2 6 8 7 3 2 2]


4.222222222222222


2.57240820062005


[7.29424985 1.32701098 0.60253033 5.76692677 7.63624717 5.99640088
 3.09114027 6.08212952 5.06353979]


[ 8.29424985  8.32701098  2.60253033 11.76692677 15.63624717 12.99640088
  6.09114027  8.08212952  7.06353979]


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [273]:
a=random.randint(1,21,(4,4))
print(a)
print('\n')
diagonal(a)

[[ 8 17 11 20]
 [10 16  1 17]
 [ 5  5 13 12]
 [17 16 10  8]]




array([ 8, 16, 13,  8])

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---